services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "testPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/var/opt/mssql/scripts/init.sql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U sa -P testPassword123 -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 60s
    entrypoint: >
      sh -c 'cp /var/opt/mssql/scripts/init.sql /tmp/init.sql &&
      /opt/mssql/bin/sqlservr &
      sleep 5 &&
      /opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U sa -P testPassword123 -i /tmp/init.sql -C &&
      wait'

  spring-auth-app:
    build: .
    container_name: spring_auth_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=authdb;encrypt=false;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: testPassword123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      spring.datasource.url: jdbc:sqlserver://mssql:1433;databaseName=authdb;encrypt=true;trustServerCertificate=true;
      spring.datasource.jdbc-url: jdbc:sqlserver://mssql:1433;databaseName=authdb;encrypt=true;trustServerCertificate=true;
      spring.datasource.username: sa
      spring.datasource.password: testPassword123
      spring.datasource.driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
    entrypoint: >
      sh -c 'java -jar app.jar'
    restart: unless-stopped

volumes:
  mssql_data:
